### ISSUE TITLE
cv::Exception in opencv_dnn module in using LeNet

### ISSUE THREAD

**Issue by tofighi** [opencv/opencv_contrib#553]
I got the following error after using [this code](http://docs.opencv.org/master/d5/de7/tutorial_dnn_googlenet.html) for LeNet

> opencv_contrib/modules/dnn/src/layers/convolution_layer.cpp:87: error: (-215) blobs[0].num() == outCn && blobs[0].channels() == inpCn / group in function allocate

For full detail please read this [post](http://stackoverflow.com/questions/35465651/how-to-use-opencv-dnn-module-for-digit-classification-by-using-lenet).

**Comment by dkurt** [comment]
It seems to me resolved.
* `mnist.prototxt` is taken from post.
* Received `.caffemodel` by `caffe train -solver mnist_solver.prototxt`
```yaml
# mnist_solver.prototxt
max_iter: 0
snapshot_prefix: "./snapshot"
solver_mode: CPU
net: "./mnist.prototxt"
```
* DNN usage (after `.caffemodel` renaming):
```python
import cv2 as cv
import numpy as np

net = cv.dnn.readNetFromCaffe('mnist.prototxt', 'mnist.caffemodel')
inp = np.random.standard_normal([1, 1, 28, 28]).astype(np.float32)
net.setInput(inp)
out = net.forward()
```
